Repository anveshmuppeda/kubernetes, pull requests merged in 2025-04, with the labels that each got.

#20 Adding New Hands On Guide for EKS IRSA
  eks/cloudformation/eks-irsa.yaml
  eks/eks-irsa/README.MD
  eks/eks-irsa/cluster.yaml
  eks/eks-irsa/ns-sa.yaml
  eks/eks-irsa/s3-access-test-app.yaml
  eks/eks-irsa/trust-relationship.json
Labels: documentation, enhancement

#21 new: Adding IRSA Arch
  eks/eks-irsa/README.MD
  eks/eks-irsa/eks.irsa.png
Labels: documentation, enhancement

#23 Updating IRSA Notes
  eks/eks-irsa/README.MD
Labels: bug, documentation

#24 Updating the EKS IRSA Arch
  eks/eks-irsa/.DS_Store
  eks/eks-irsa/README.MD
  eks/eks-irsa/eks.irsa.png
  eks/pod-identity/README.MD
Labels: bug, documentation

#27 Adding # Hands‑On Guide to Karpenter on AWS EKS
  eks/karpenter/README.MD
Labels: documentation, enhancement

#30 Updating "Karpenter + EKS: The Smart Way to Scale" Guide
  eks/cloudformation/eks-karpeneter.yaml
  eks/karpenter/README.MD
  eks/karpenter/images/.DS_Store
  eks/karpenter/images/after-fleet-manager.png
  eks/karpenter/images/after-nodes.png
  eks/karpenter/images/before-fleet-manager.png
  eks/karpenter/images/before-nodes.png
  eks/karpenter/images/delete-node.png
  eks/karpenter/images/eks.karpenter.arch.png
  eks/karpenter/images/nodeclaim-status.png
  eks/karpenter/images/pods-status.png
  eks/karpenter/nodepool.yaml
Labels: documentation, enhancement

#31 Adding New Guide for # AWS EKS Pod Identity vs IRSA
  eks/Pod.Identity.vs.IRSA.MD
  eks/README.MD
  eks/deployment.yaml
  images/eks.podidentity.vs.irsa.png
Labels: documentation, enhancement

#33 Update EKS Guides
  eks/cloudformation/eks-karpenter.cft.yaml
  eks/karpenter/README.MD
Labels: documentation, enhancement

#34 Update EKS Karpenter Source Arch
  eks/karpenter/images/eks.karpenter.arch.png
Labels: documentation

#39 Update Different Types of Cluster Setup Guides
  README.md
  assets/eks-fargate.png
  assets/eks.podidentity.vs.irsa.png
  assets/kubeadm-cluster-setup.png
  assets/kubernetes-architecture.png
  cluster-setup/README.MD
  cluster-setup/eks/README.md
  cluster-setup/kind/README.md
  cluster-setup/kubeadm/README.md
  cluster-setup/minikube/README.md
  eks/Pod.Identity.vs.IRSA.MD
  eks/README.MD
Labels: documentation, enhancement

#40 Update Main Readme Content
  README.md
  cluster-setup/README.MD
Labels: documentation

#41 Update README with latest Kubernetes blogs
  README.md
Labels: documentation

#44 Adding FluxCD Source Code
  .github/WorkFlow.MD
  .github/workflows/docker-build-push-update.yaml
  .github/workflows/docker-build-push.yaml
  .github/workflows/update_readme.yml
  README.md
  fluxcd/README.MD
  fluxcd/repos/app1/README.MD
  fluxcd/repos/app1/deploy/app1-deployment.yaml
  fluxcd/repos/app1/deploy/app1-service.yaml
  fluxcd/repos/app1/src/Dockerfile
  fluxcd/repos/app1/src/html/index.html
  fluxcd/repos/app1/src/html/k8s-logo.png
  fluxcd/repos/app1/src/html/styles.css
  fluxcd/repos/app2/README.MD
  fluxcd/repos/app2/src/Dockerfile
  fluxcd/repos/app2/src/html/index.html
  fluxcd/repos/app2/src/html/k8s-logo.png
  fluxcd/repos/app2/src/html/styles.css
  fluxcd/repos/infra-repo/apps/app1/gitrepository.yaml
  fluxcd/repos/infra-repo/apps/app1/kustomization.yaml
  fluxcd/repos/infra-repo/apps/app2/deploy/app2-deployment.yaml
  fluxcd/repos/infra-repo/apps/app2/deploy/app2-service.yaml
  fluxcd/repos/infra-repo/apps/app2/gitrepository.yaml
  fluxcd/repos/infra-repo/apps/app2/imagepolicy.yaml
  fluxcd/repos/infra-repo/apps/app2/imagerepository.yaml
  fluxcd/repos/infra-repo/apps/app2/imageupdateautomation.yaml
  fluxcd/repos/infra-repo/apps/app2/kustomization.yaml
  fluxcd/repos/infra-repo/clusters/dev/flux-system/gotk-components.yaml
  fluxcd/repos/infra-repo/clusters/staging/flux-system/gotk-components.yaml
Labels: documentation, enhancement

#49 Update Main Readme
  CONTRIBUTING.md
  README.md
  fluxcd/repos/app1/deploy/app1-deployment.yaml
  fluxcd/repos/app3/charts/simple-chart/values.yaml
  fluxcd/repos/infra-repo/apps/app3/helmrelease.yaml
Labels: documentation

#65 Feature/eks alb controller
  eks/alb-controller/README.MD
  eks/alb-controller/assets/lbc-overview.png
  eks/alb-controller/iam-policy.json
  eks/alb-controller/manifests/Ingress-resource.yaml
  eks/alb-controller/manifests/Test-App.yaml
  eks/alb-controller/manifests/Test-App2.yaml
  eks/alb-controller/manifests/Test-App3.yaml
Labels: documentation, enhancement, help wanted

#110 fix: Update README to link directly to the GitHub repository for enhanced access
  README.md
Labels: bug, documentation
